FROM python:3.11-slim

WORKDIR /app

# Install requirements
COPY bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY bot/src ./src

EXPOSE 5001

ENV PYTHONUNBUFFERED=1

CMD ["python", "src/main.py"]
